### ISSUE TITLE
Props not passed when trying to use Chaos in production

### ISSUE THREAD

**Issue by etienne-dldc** [jchiatt/react-chaos#8]
Hey, I was looking a the code and I noticed that here: https://github.com/jchiatt/react-chaos/blob/master/src/index.tsx#L17
The props are not passed down to the `WrappedComponent`. It should probably be

```js
return (props) => <WrappedComponent {...props} />;
```
or just:
```
return WrappedComponent
```

**Comment by jchiatt** [comment]
@etienne-dldc thanks for reporting!
